name: "Build and test"

on: pull_request

jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Install Danger
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install danger/tap/danger-swift
      - name: Run Danger
        run: swift run danger-swift ci

