name: "Build and test"

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Swift on Linux
        uses: sersoft-gmbh/swifty-linux-action@v1.3.0
        with:
          release-version: '5.5'
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Danger JS
        uses: danger/danger-js@9.1.6
      - name: Danger
        run: swift run danger-swift ci
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

