name: "Build and test"

on: pull_request

jobs:
  build:
    runs-on: macos-13
    env:
      GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      HOMEBREW_NO_AUTO_UPDATE: 1
      DANGER_SWIFT_PERIPHERY_DEBUG: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Build
#        run: swift build
#      - name: Test
#        run: swift test
      - name: Install Danger
        run: brew install danger/tap/danger-swift
      - name: Run Danger
        run: swift run danger-swift ci

